-------------------- Log Start | Wed Mar 27 12:12:03 2024 --------------------
data_path: /home/Pi/printer_data
is_default_data_path: False
config_file: /home/Pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: ed66581bdb9442a8ba66cabe74f1bd44
unix_socket_path: /home/Pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-186-g2641fc5
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/Pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager]
refresh_interval = 168
enable_auto_refresh = True

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

[update_manager sonar]
type = git_repo
path = ~/sonar
origin = https://github.com/mainsail-crew/sonar.git
primary_branch = main
managed_services = sonar
install_script = tools/install.sh

[update_manager klipper-macros]
type = git_repo
origin = https://github.com/jschuh/klipper-macros.git
path = ~/printer_data/config/klipper-macros
primary_branch = main
is_system_service = False
managed_services = klipper

#################################################################
All Configuration Files:
/home/Pi/printer_data/config/moonraker.conf
#################################################################
Unsafe Shutdown Count: 13

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: aarch64
  cpu_desc: 
  serial_number: 100000008ec46bbe
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713732
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SC32G
  product_revision: 8.0
  serial_number: 59bac505
  manufacturer_date: 7/2022
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Raspbian GNU/Linux 11 (bullseye)
  id: raspbian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: debian
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.2.1', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'system.slice', 'sysinit.target']
**After=['basic.target', 'system.slice', 'klipper.service', 'sysinit.target', 'network-online.target', 'systemd-journald.socket']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/Pi/printer_data/systemd/moonraker.env
**ExecStart=/home/Pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=Pi

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['basic.target', '-.mount', 'system.slice', 'sysinit.target', 'network-online.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/Pi/printer_data/systemd/klipper.env
**ExecStart=/home/Pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/Pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=Pi
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
Git Repo klipper: Warnings detected:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
Git Repo mainsail-config: No warnings detected
Git Repo sonar: No warnings detected
Git Repo klipper-macros: No warnings detected
Klipper Version: v0.11.0-303-g67499853-dirty
2024-03-27 08:12:03,789 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xf68701d8>, <Task finished name='Task-49063043' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 08:12:06,862 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe8ff4028>, <Task finished name='Task-49063131' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 08:12:09,933 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe8ff4340>, <Task finished name='Task-49063221' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 08:12:14,649 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': Timeout while connecting
2024-03-27 08:12:19,944 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7395fa0>, <Task finished name='Task-49063309' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 08:12:20,013 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe8ff4148>, <Task finished name='Task-49063399' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 13:37:57,329 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-03-27 13:37:57,331 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-03-27 13:40:57,526 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.18
2024-03-27 13:40:57,529 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.18
2024-03-27 13:42:14,170 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7395d60>, <Task finished name='Task-49379461' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 13:42:14,663 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': Timeout while connecting
2024-03-27 13:42:14,669 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe8ff4418>, <Task finished name='Task-49379554' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-03-27 13:42:16,686 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-03-27 13:42:17,614 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-03-27 13:42:17,616 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-03-27 13:42:18,710 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2024-03-27 13:42:27,617 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.18
2024-03-27 13:42:27,619 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.18
2024-03-27 13:42:47,621 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-03-27 13:42:47,623 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-03-27 13:42:57,651 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.18
2024-03-27 13:42:57,654 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.18
2024-03-27 23:42:08,583 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-03-27 23:42:08,585 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-03-27 23:42:28,609 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.18
2024-03-27 23:42:28,612 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.18
