-------------------- Log Start | Sun Oct 22 04:00:00 2023 --------------------
data_path: /home/Pi/printer_data
is_default_data_path: False
config_file: /home/Pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: ed66581bdb9442a8ba66cabe74f1bd44
unix_socket_path: /home/Pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-186-g2641fc5
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/Pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager]
refresh_interval = 168
enable_auto_refresh = True

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

[update_manager sonar]
type = git_repo
path = ~/sonar
origin = https://github.com/mainsail-crew/sonar.git
primary_branch = main
managed_services = sonar
install_script = tools/install.sh

[update_manager klipper-macros]
type = git_repo
origin = https://github.com/jschuh/klipper-macros.git
path = ~/printer_data/config/klipper-macros
primary_branch = main
is_system_service = False
managed_services = klipper

#################################################################
All Configuration Files:
/home/Pi/printer_data/config/moonraker.conf
#################################################################
Unsafe Shutdown Count: 4

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: aarch64
  cpu_desc: 
  serial_number: 100000008ec46bbe
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713732
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SC32G
  product_revision: 8.0
  serial_number: 59bac505
  manufacturer_date: 7/2022
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Raspbian GNU/Linux 11 (bullseye)
  id: raspbian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: debian
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.2.1', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', 'network-online.target']
**After=['klipper.service', 'system.slice', 'systemd-journald.socket', 'basic.target', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/Pi/printer_data/systemd/moonraker.env
**ExecStart=/home/Pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=Pi

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'system.slice', 'sysinit.target']
**After=['system.slice', 'systemd-journald.socket', 'basic.target', 'network-online.target', 'sysinit.target', '-.mount']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/Pi/printer_data/systemd/klipper.env
**ExecStart=/home/Pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/Pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=Pi
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
Git Repo klipper: No warnings detected
Git Repo mainsail-config: No warnings detected
Git Repo sonar: No warnings detected
Git Repo klipper-macros: No warnings detected
Klipper Version: v0.11.0-303-g67499853-dirty
2023-10-22 00:00:00,812 [update_manager.py:_handle_auto_refresh()] - Klippy is printing, auto refresh aborted
2023-10-22 00:12:55,678 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 00:12:55,680 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 00:13:05,692 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 00:13:05,694 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 00:14:35,789 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 00:14:35,792 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 00:14:55,813 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 00:14:55,816 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 00:15:00,277 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.112
2023-10-22 00:25:00,280 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.12
2023-10-22 00:43:04,764 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.112
2023-10-22 00:43:49,777 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 00:43:49,882 [app.py:post()] - Processing Uploaded File: printer.cfg
2023-10-22 00:43:49,892 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 121.30ms
2023-10-22 00:43:51,099 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 00:43:52,360 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 00:43:56,743 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 00:43:56,745 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 00:43:56,994 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 00:43:57,266 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 00:43:57,746 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 00:47:45,813 [websockets.py:on_close()] - Websocket Closed: ID: 4141318592 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 2.83
2023-10-22 00:47:46,301 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 4.90ms
2023-10-22 00:47:46,303 [websockets.py:open()] - Websocket Opened: ID: 3912212072, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 00:47:46,357 [websockets.py:_handle_identify()] - Websocket 3912212072 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 00:53:41,623 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 00:53:41,630 [app.py:post()] - Processing Uploaded File: printer.cfg
2023-10-22 00:53:41,643 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 22.21ms
2023-10-22 00:59:15,745 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.gcode.script, Code: 400, Message: {'error': 'WebRequestError', 'message': 'Move out of range: 0.000 240.000 30.000 [0.000]'}
2023-10-22 01:04:07,525 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 01:04:08,789 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 01:04:12,934 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 01:04:12,935 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 01:04:13,185 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 01:04:13,452 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 01:04:14,026 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 01:11:03,816 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 01:11:04,022 [app.py:post()] - Processing Uploaded File: /x10 clips.gcode
2023-10-22 01:11:04,231 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 01:11:04,281 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "x10 clips.gcode") successfully finished
2023-10-22 01:11:04,290 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 476.74ms
2023-10-22 01:11:04,422 [job_state.py:_status_update()] - Job Started: x10 clips.gcode
2023-10-22 01:15:06,054 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 6.11ms
2023-10-22 01:15:06,055 [websockets.py:open()] - Websocket Opened: ID: 3902003424, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 01:15:06,071 [websockets.py:_handle_identify()] - Websocket 3902003424 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 01:57:23,817 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 01:57:23,829 [app.py:post()] - Processing Uploaded File: printer.cfg
2023-10-22 01:57:23,841 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 27.09ms
2023-10-22 01:57:31,320 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 01:57:32,581 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 01:57:36,976 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 01:57:36,978 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 01:57:37,228 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 01:57:37,503 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 01:57:38,621 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 01:59:33,944 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2023-10-22 01:59:33,954 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1697954344.846767, Usage: 2.39%, Memory: 28468 kB
System Time: 1697954345.848128, Usage: 2.31%, Memory: 28468 kB
System Time: 1697954346.849597, Usage: 2.88%, Memory: 28468 kB
System Time: 1697954347.851007, Usage: 2.3%, Memory: 28468 kB
System Time: 1697954348.852305, Usage: 2.25%, Memory: 28468 kB
System Time: 1697954349.853467, Usage: 2.31%, Memory: 28468 kB
System Time: 1697954350.854954, Usage: 2.29%, Memory: 28468 kB
System Time: 1697954351.855831, Usage: 2.29%, Memory: 28468 kB
System Time: 1697954352.856881, Usage: 2.25%, Memory: 28468 kB
System Time: 1697954353.859381, Usage: 4.4%, Memory: 28468 kB
System Time: 1697954354.860640, Usage: 2.37%, Memory: 28468 kB
System Time: 1697954355.863179, Usage: 2.28%, Memory: 28468 kB
System Time: 1697954356.865354, Usage: 3.0%, Memory: 28468 kB
System Time: 1697954357.867820, Usage: 2.38%, Memory: 28468 kB
System Time: 1697954358.870096, Usage: 2.37%, Memory: 28468 kB
System Time: 1697954359.871031, Usage: 2.32%, Memory: 28468 kB
System Time: 1697954360.872125, Usage: 2.33%, Memory: 28468 kB
System Time: 1697954361.873158, Usage: 2.39%, Memory: 28468 kB
System Time: 1697954362.873950, Usage: 2.37%, Memory: 28468 kB
System Time: 1697954363.876348, Usage: 4.06%, Memory: 28468 kB
System Time: 1697954364.876669, Usage: 2.49%, Memory: 28468 kB
System Time: 1697954365.877639, Usage: 2.35%, Memory: 28468 kB
System Time: 1697954366.878213, Usage: 2.87%, Memory: 28468 kB
System Time: 1697954367.878780, Usage: 2.29%, Memory: 28468 kB
System Time: 1697954368.876353, Usage: 2.25%, Memory: 28468 kB
System Time: 1697954369.876647, Usage: 0.98%, Memory: 28468 kB
System Time: 1697954370.878062, Usage: 0.95%, Memory: 28468 kB
System Time: 1697954371.879470, Usage: 0.97%, Memory: 28468 kB
System Time: 1697954372.879872, Usage: 0.97%, Memory: 28468 kB
System Time: 1697954373.884213, Usage: 2.22%, Memory: 28468 kB
CPU Temperature: 55.017
2023-10-22 01:59:33,956 [proc_stats.py:_handle_shutdown()] - Throttled Flags: 
2023-10-22 02:01:16,250 [websockets.py:write_to_socket()] - Websocket closed while writing: 3902003424
2023-10-22 02:01:16,501 [websockets.py:write_to_socket()] - Websocket closed while writing: 3912212072
2023-10-22 02:01:21,058 [websockets.py:on_close()] - Websocket Closed: ID: 3902003424 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.98
2023-10-22 02:01:21,305 [websockets.py:on_close()] - Websocket Closed: ID: 3912212072 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.98
2023-10-22 02:13:43,913 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 02:13:43,915 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 02:13:53,924 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 02:13:53,926 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 02:28:34,910 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 02:28:34,912 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 02:28:44,920 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 02:28:44,922 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 02:43:35,877 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 02:43:35,879 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 02:43:45,885 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 02:43:45,888 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 02:58:36,808 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 02:58:36,810 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 02:58:46,821 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 02:58:46,824 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 03:00:00,314 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.112
2023-10-22 04:13:31,581 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 04:13:31,583 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 04:13:41,593 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 04:13:41,596 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 05:13:55,389 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 05:13:55,392 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 05:14:05,401 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 05:14:05,404 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 05:43:47,245 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 05:43:47,245 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 05:43:57,273 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 05:43:57,276 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 06:44:01,044 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 06:44:01,045 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 06:44:11,070 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 06:44:11,072 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 07:43:54,897 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 07:43:54,900 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 07:44:04,913 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 07:44:04,916 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 08:13:56,854 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 08:13:56,856 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 08:14:06,862 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 08:14:06,865 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 08:43:48,711 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 08:43:48,713 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 08:43:58,723 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 08:43:58,725 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 08:58:39,634 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 08:58:39,636 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 08:58:49,643 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 08:58:49,646 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 09:13:40,581 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 09:13:40,584 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 09:13:50,588 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 09:13:50,590 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 10:13:44,342 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 10:13:44,343 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 10:13:54,369 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 10:13:54,371 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 10:43:22,033 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.112
2023-10-22 10:43:22,037 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 7.33ms
2023-10-22 10:43:22,038 [websockets.py:open()] - Websocket Opened: ID: 4138818504, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 10:43:22,049 [websockets.py:_handle_identify()] - Websocket 4138818504 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 10:43:22,739 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 1.86ms
2023-10-22 10:43:22,739 [websockets.py:open()] - Websocket Opened: ID: 4138815552, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 10:43:22,760 [websockets.py:_handle_identify()] - Websocket 4138815552 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 10:43:56,283 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 10:43:56,284 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 10:44:06,309 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 10:44:06,311 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 10:49:21,900 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 10:49:22,691 [app.py:post()] - Processing Uploaded File: /Custom Speed Tower - Print Speed 50.0-250.0x25.0.gcode
2023-10-22 10:49:22,911 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 10:49:22,962 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "Custom Speed Tower - Print Speed 50.0-250.0x25.0.gcode") successfully finished
2023-10-22 10:49:22,966 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 1067.07ms
2023-10-22 10:51:23,235 [websockets.py:on_close()] - Websocket Closed: ID: 4138815552 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 0.48
2023-10-22 10:51:23,613 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 5.05ms
2023-10-22 10:51:23,615 [websockets.py:open()] - Websocket Opened: ID: 4138817880, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 10:51:23,647 [websockets.py:_handle_identify()] - Websocket 4138817880 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 10:51:31,309 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 10:51:32,571 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 10:51:36,982 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 10:51:36,984 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 10:51:37,233 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 10:51:37,509 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 10:51:38,752 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 10:52:56,975 [job_state.py:_status_update()] - Job Started: Custom Speed Tower - Print Speed 50.0-250.0x25.0.gcode
2023-10-22 11:39:04,443 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.12
2023-10-22 11:39:04,446 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 6.78ms
2023-10-22 11:39:04,447 [websockets.py:open()] - Websocket Opened: ID: 4141329760, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 11:39:04,457 [websockets.py:_handle_identify()] - Websocket 4141329760 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 11:39:34,060 [websockets.py:on_close()] - Websocket Closed: ID: 4141329760 Close Code: None, Close Reason: None, Pong Time Elapsed: 9.59
2023-10-22 11:49:12,872 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.49ms
2023-10-22 11:49:12,873 [websockets.py:open()] - Websocket Opened: ID: 4141319816, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 11:49:12,889 [websockets.py:_handle_identify()] - Websocket 4141319816 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 11:49:27,086 [websockets.py:on_close()] - Websocket Closed: ID: 4141319816 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.03
2023-10-22 11:58:51,633 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 11:58:51,635 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 11:59:01,652 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 11:59:01,654 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 12:07:33,683 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.57ms
2023-10-22 12:07:33,684 [websockets.py:open()] - Websocket Opened: ID: 3902146784, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 12:07:33,704 [websockets.py:_handle_identify()] - Websocket 3902146784 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 12:08:06,049 [websockets.py:on_close()] - Websocket Closed: ID: 3902146784 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.29
2023-10-22 12:10:00,451 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.112
2023-10-22 12:23:33,156 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.35ms
2023-10-22 12:23:33,157 [websockets.py:open()] - Websocket Opened: ID: 3902145968, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 12:23:33,360 [websockets.py:_handle_identify()] - Websocket 3902145968 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 12:23:40,102 [websockets.py:on_close()] - Websocket Closed: ID: 3902145968 Close Code: None, Close Reason: None, Pong Time Elapsed: 6.95
2023-10-22 12:28:43,638 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 12:28:43,643 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 12:28:53,649 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 12:28:53,651 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 12:41:11,500 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.52ms
2023-10-22 12:41:11,501 [websockets.py:open()] - Websocket Opened: ID: 3902146088, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 12:41:11,515 [websockets.py:_handle_identify()] - Websocket 3902146088 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 12:42:07,849 [websockets.py:on_close()] - Websocket Closed: ID: 3902146088 Close Code: None, Close Reason: None, Pong Time Elapsed: 6.29
2023-10-22 12:44:17,105 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.112
2023-10-22 12:53:25,825 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 12:53:26,079 [app.py:post()] - Processing Uploaded File: /CE3S1PRO_klippt-cable-clip-medium.gcode
2023-10-22 12:53:26,258 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 12:53:26,308 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "CE3S1PRO_klippt-cable-clip-medium.gcode") successfully finished
2023-10-22 12:53:26,318 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 494.54ms
2023-10-22 12:53:26,505 [job_state.py:_status_update()] - Job Started: CE3S1PRO_klippt-cable-clip-medium.gcode
2023-10-22 12:58:55,711 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 12:58:55,711 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 12:59:05,744 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 12:59:05,748 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 13:13:36,729 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 13:13:36,731 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 13:13:46,745 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 13:13:46,748 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 13:28:37,773 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 13:28:37,775 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 13:28:47,785 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 13:28:47,788 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 13:38:58,008 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 13:38:59,421 [app.py:post()] - Processing Uploaded File: /CE3S1PRO_klippt-screw-base.gcode
2023-10-22 13:38:59,604 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 13:38:59,655 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "CE3S1PRO_klippt-screw-base.gcode") successfully finished
2023-10-22 13:38:59,663 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 1656.90ms
2023-10-22 13:38:59,879 [job_state.py:_status_update()] - Job Started: CE3S1PRO_klippt-screw-base.gcode
2023-10-22 13:45:00,470 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.12
2023-10-22 13:58:49,822 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 13:58:49,824 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 13:58:59,831 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 13:58:59,833 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 14:13:13,768 [websockets.py:write_to_socket()] - Websocket closed while writing: 4138817880
2023-10-22 14:13:15,999 [websockets.py:on_close()] - Websocket Closed: ID: 4138817880 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.68
2023-10-22 14:13:40,827 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 14:13:40,829 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 14:13:50,838 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 14:13:50,841 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 14:40:00,483 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.112
2023-10-22 14:54:01,112 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.12
2023-10-22 14:54:01,116 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 7.50ms
2023-10-22 14:54:01,117 [websockets.py:open()] - Websocket Opened: ID: 3902154280, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 14:54:01,140 [websockets.py:_handle_identify()] - Websocket 3902154280 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 14:54:19,714 [websockets.py:on_close()] - Websocket Closed: ID: 3902154280 Close Code: None, Close Reason: None, Pong Time Elapsed: 8.54
2023-10-22 15:00:34,417 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.83ms
2023-10-22 15:00:34,418 [websockets.py:open()] - Websocket Opened: ID: 3902156632, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 15:00:34,433 [websockets.py:_handle_identify()] - Websocket 3902156632 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 15:00:43,458 [websockets.py:on_close()] - Websocket Closed: ID: 3902156632 Close Code: None, Close Reason: None, Pong Time Elapsed: 9.04
2023-10-22 15:28:45,912 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 15:28:45,914 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 15:28:55,921 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 15:28:55,924 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 15:43:36,885 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 15:43:36,887 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 15:43:46,899 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 15:43:46,902 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 16:05:00,505 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.12
2023-10-22 16:13:48,966 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 16:13:48,968 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 16:13:58,969 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 16:13:58,974 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 16:30:22,048 [websockets.py:write_to_socket()] - Websocket closed while writing: 4138818504
2023-10-22 16:30:24,884 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fef658>, <Task finished name='Task-1481892' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:27,042 [websockets.py:on_close()] - Websocket Closed: ID: 4138818504 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.98
2023-10-22 16:30:27,330 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': Timeout while connecting
2023-10-22 16:30:27,956 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fef580>, <Task finished name='Task-1482032' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:34,100 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fed148>, <Task finished name='Task-1482181' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:40,244 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895a9b8>, <Task finished name='Task-1482321' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:46,388 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895aad8>, <Task finished name='Task-1482469' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:49,460 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fef0b8>, <Task finished name='Task-1482571' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:30:54,347 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': Timeout while connecting
2023-10-22 16:30:55,604 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fef6e8>, <Task finished name='Task-1482661' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:01,748 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895a580>, <Task finished name='Task-1482749' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:07,892 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895a8e0>, <Task finished name='Task-1482838' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:10,964 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895a340>, <Task finished name='Task-1482926' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:15,971 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fef070>, <Task finished name='Task-1483010' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:15,971 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7fefb20>, <Task finished name='Task-1483094' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:15,971 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895a610>, <Task finished name='Task-1483187' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:15,972 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe895ad18>, <Task finished name='Task-1483277' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:16,361 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2023-10-22 16:31:20,138 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 16:31:20,140 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 16:31:30,146 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 16:31:30,149 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 16:39:50,360 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.112
2023-10-22 16:39:50,363 [app.py:log_request()] - 101 GET /websocket (192.168.0.112) [_TRUSTED_USER_] 7.05ms
2023-10-22 16:39:50,364 [websockets.py:open()] - Websocket Opened: ID: 3902156152, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0, Host Name: 192.168.0.195
2023-10-22 16:39:50,373 [websockets.py:_handle_identify()] - Websocket 3902156152 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 16:44:11,025 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 16:44:11,027 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 16:44:21,025 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 16:44:21,027 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 16:59:12,035 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 16:59:12,037 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 16:59:22,045 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 16:59:22,048 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 17:05:27,243 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 17:05:29,032 [app.py:post()] - Processing Uploaded File: /PETG - Mix of cable management clips.gcode
2023-10-22 17:05:29,211 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 17:05:29,261 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "PETG - Mix of cable management clips.gcode") successfully finished
2023-10-22 17:05:29,271 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 2030.00ms
2023-10-22 17:05:29,349 [job_state.py:_status_update()] - Job Started: PETG - Mix of cable management clips.gcode
2023-10-22 17:08:12,111 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2023-10-22 17:08:12,126 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1698008862.609816, Usage: 2.11%, Memory: 29472 kB
System Time: 1698008863.611800, Usage: 4.28%, Memory: 29472 kB
System Time: 1698008864.611858, Usage: 2.24%, Memory: 29472 kB
System Time: 1698008865.613047, Usage: 2.18%, Memory: 29472 kB
System Time: 1698008866.614259, Usage: 2.15%, Memory: 29472 kB
System Time: 1698008867.615170, Usage: 2.19%, Memory: 29472 kB
System Time: 1698008868.616730, Usage: 2.09%, Memory: 29472 kB
System Time: 1698008869.617359, Usage: 2.22%, Memory: 29472 kB
System Time: 1698008870.620374, Usage: 2.36%, Memory: 29472 kB
System Time: 1698008871.620696, Usage: 2.18%, Memory: 29472 kB
System Time: 1698008872.621285, Usage: 2.12%, Memory: 29472 kB
System Time: 1698008873.622345, Usage: 4.06%, Memory: 29472 kB
System Time: 1698008874.622233, Usage: 2.16%, Memory: 29472 kB
System Time: 1698008875.624554, Usage: 2.06%, Memory: 29472 kB
System Time: 1698008876.625613, Usage: 2.16%, Memory: 29472 kB
System Time: 1698008877.625640, Usage: 2.15%, Memory: 29472 kB
System Time: 1698008878.627295, Usage: 2.09%, Memory: 29472 kB
System Time: 1698008879.628363, Usage: 2.15%, Memory: 29472 kB
System Time: 1698008880.628730, Usage: 2.5%, Memory: 29472 kB
System Time: 1698008881.629841, Usage: 2.04%, Memory: 29472 kB
System Time: 1698008882.631464, Usage: 2.02%, Memory: 29472 kB
System Time: 1698008883.633578, Usage: 4.34%, Memory: 29472 kB
System Time: 1698008884.633688, Usage: 2.62%, Memory: 29472 kB
System Time: 1698008885.634567, Usage: 2.17%, Memory: 29472 kB
System Time: 1698008886.635043, Usage: 2.13%, Memory: 29472 kB
System Time: 1698008887.635501, Usage: 2.17%, Memory: 29472 kB
System Time: 1698008888.637123, Usage: 2.12%, Memory: 29472 kB
System Time: 1698008889.638152, Usage: 2.26%, Memory: 29472 kB
System Time: 1698008890.639409, Usage: 2.5%, Memory: 29472 kB
System Time: 1698008891.639991, Usage: 2.26%, Memory: 29472 kB
CPU Temperature: 51.608
2023-10-22 17:08:12,129 [proc_stats.py:_handle_shutdown()] - Throttled Flags: 
2023-10-22 17:08:12,193 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.print.pause, Code: 400, Message: {'error': 'WebRequestError', 'message': 'Shutdown due to webhooks request\nOnce the underlying issue is corrected, use the\n"FIRMWARE_RESTART" command to reset the firmware, reload the\nconfig, and restart the host software.\nPrinter is shutdown\n'}
2023-10-22 17:08:17,768 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:08:19,031 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:08:22,172 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:08:22,173 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:08:22,175 [klippy_connection.py:_check_ready()] - 
Can not update MCU 'mcu' config as it is shutdown
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2023-10-22 17:08:26,617 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:08:27,876 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:08:32,274 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:08:32,275 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:08:32,525 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 17:08:32,799 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 17:08:33,292 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 17:08:38,797 [job_state.py:_status_update()] - Job Started: PETG - Mix of cable management clips.gcode
2023-10-22 17:09:14,409 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2023-10-22 17:09:14,419 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1698008924.676182, Usage: 2.08%, Memory: 29528 kB
System Time: 1698008925.677213, Usage: 2.0%, Memory: 29528 kB
System Time: 1698008926.678392, Usage: 1.93%, Memory: 29528 kB
System Time: 1698008927.679679, Usage: 1.95%, Memory: 29528 kB
System Time: 1698008928.679552, Usage: 1.9%, Memory: 29528 kB
System Time: 1698008929.680757, Usage: 1.89%, Memory: 29528 kB
System Time: 1698008930.682015, Usage: 2.16%, Memory: 29528 kB
System Time: 1698008931.682610, Usage: 1.98%, Memory: 29528 kB
System Time: 1698008932.682555, Usage: 1.93%, Memory: 29528 kB
System Time: 1698008933.684397, Usage: 3.72%, Memory: 29528 kB
System Time: 1698008934.684098, Usage: 1.96%, Memory: 29528 kB
System Time: 1698008935.686178, Usage: 3.65%, Memory: 29528 kB
System Time: 1698008936.686811, Usage: 1.98%, Memory: 29528 kB
System Time: 1698008937.686623, Usage: 2.03%, Memory: 29528 kB
System Time: 1698008938.688354, Usage: 1.82%, Memory: 29528 kB
System Time: 1698008939.690954, Usage: 1.93%, Memory: 29528 kB
System Time: 1698008940.692441, Usage: 2.19%, Memory: 29528 kB
System Time: 1698008941.693706, Usage: 1.98%, Memory: 29528 kB
System Time: 1698008942.694319, Usage: 2.1%, Memory: 29528 kB
System Time: 1698008943.696259, Usage: 4.38%, Memory: 29528 kB
System Time: 1698008944.697065, Usage: 2.28%, Memory: 29528 kB
System Time: 1698008945.698045, Usage: 2.18%, Memory: 29528 kB
System Time: 1698008946.699260, Usage: 2.23%, Memory: 29528 kB
System Time: 1698008947.700131, Usage: 2.25%, Memory: 29528 kB
System Time: 1698008948.701211, Usage: 2.19%, Memory: 29528 kB
System Time: 1698008949.701556, Usage: 2.18%, Memory: 29528 kB
System Time: 1698008950.702506, Usage: 2.42%, Memory: 29528 kB
System Time: 1698008951.704108, Usage: 2.12%, Memory: 29528 kB
System Time: 1698008952.705173, Usage: 2.44%, Memory: 29528 kB
System Time: 1698008953.707808, Usage: 4.22%, Memory: 29528 kB
CPU Temperature: 51.608
2023-10-22 17:09:14,424 [proc_stats.py:_handle_shutdown()] - Throttled Flags: 
2023-10-22 17:09:14,920 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.print.pause, Code: 400, Message: {'error': 'WebRequestError', 'message': 'Shutdown due to webhooks request\nOnce the underlying issue is corrected, use the\n"FIRMWARE_RESTART" command to reset the firmware, reload the\nconfig, and restart the host software.\nPrinter is shutdown\n'}
2023-10-22 17:09:19,057 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:09:20,318 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:09:22,727 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:09:23,984 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:09:28,112 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:09:28,113 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:09:28,363 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 17:09:28,629 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 17:09:29,182 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 17:11:37,249 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 17:11:37,256 [app.py:post()] - Processing Uploaded File: printer.cfg
2023-10-22 17:11:37,269 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 23.16ms
2023-10-22 17:11:38,318 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:11:39,578 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:11:43,981 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:11:43,983 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:11:44,233 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 17:11:44,512 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 17:11:45,249 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 17:11:51,254 [job_state.py:_status_update()] - Job Started: PETG - Mix of cable management clips.gcode
2023-10-22 17:14:33,076 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 17:14:33,078 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 17:14:43,088 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 17:14:43,091 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 17:23:57,002 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.gcode.script, Code: 400, Message: {'error': 'WebRequestError', 'message': 'Must home axis first: 0.000 235.000 10.000 [219.959]'}
2023-10-22 17:27:31,713 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 17:27:31,721 [app.py:post()] - Processing Uploaded File: printer.cfg
2023-10-22 17:27:31,734 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 24.59ms
2023-10-22 17:27:32,787 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:27:34,047 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:27:38,453 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:27:38,454 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:27:38,704 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 17:27:39,008 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 17:27:39,470 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 17:30:22,888 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-10-22 17:30:24,144 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-10-22 17:30:28,247 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-10-22 17:30:28,249 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-10-22 17:30:28,498 [job_state.py:_handle_started()] - Job state initialized: standby
2023-10-22 17:30:28,788 [klippy_connection.py:_check_ready()] - Klippy ready
2023-10-22 17:30:29,318 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2023-10-22 17:32:10,219 [app.py:prepare()] - Upload Request Received from 192.168.0.112
2023-10-22 17:32:11,075 [app.py:post()] - Processing Uploaded File: /PETG - x4 Large cable clip.gcode
2023-10-22 17:32:11,258 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 17:32:11,310 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "PETG - x4 Large cable clip.gcode") successfully finished
2023-10-22 17:32:11,319 [app.py:log_request()] - 201 POST /server/files/upload (192.168.0.112) [_TRUSTED_USER_] 1101.41ms
2023-10-22 17:32:11,349 [job_state.py:_status_update()] - Job Started: PETG - x4 Large cable clip.gcode
2023-10-22 17:32:49,661 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2023-10-22 17:32:49,713 [shell_command.py:_check_proc_success()] - Command (/home/Pi/moonraker-env/bin/python /home/Pi/moonraker/moonraker/components/file_manager/metadata.py -p /home/Pi/printer_data/gcodes -f "PETG - x4 Large cable clip.gcode") successfully finished
2023-10-22 17:59:16,062 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 17:59:16,063 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 17:59:26,087 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 17:59:26,089 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 18:14:27,105 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 18:14:27,107 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 18:14:37,112 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 18:14:37,114 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 18:29:28,095 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 18:29:28,097 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 18:29:38,099 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 18:29:38,102 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 18:35:00,538 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.112
2023-10-22 18:45:34,568 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.12
2023-10-22 18:45:34,571 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 5.87ms
2023-10-22 18:45:34,572 [websockets.py:open()] - Websocket Opened: ID: 3881073368, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 18:45:34,591 [websockets.py:_handle_identify()] - Websocket 3881073368 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 18:45:45,166 [websockets.py:on_close()] - Websocket Closed: ID: 3881073368 Close Code: None, Close Reason: None, Pong Time Elapsed: 10.60
2023-10-22 18:48:14,235 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 6.26ms
2023-10-22 18:48:14,236 [websockets.py:open()] - Websocket Opened: ID: 4141329880, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 18:48:14,281 [websockets.py:_handle_identify()] - Websocket 4141329880 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 18:48:22,037 [websockets.py:on_close()] - Websocket Closed: ID: 4141329880 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.80
2023-10-22 18:48:27,413 [app.py:log_request()] - 101 GET /websocket (192.168.0.12) [_TRUSTED_USER_] 6.63ms
2023-10-22 18:48:27,415 [websockets.py:open()] - Websocket Opened: ID: 4141326640, Proxied: True, User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1, Host Name: 192.168.0.195
2023-10-22 18:48:27,692 [websockets.py:_handle_identify()] - Websocket 4141326640 Client Identified - Name: mainsail, Version: 2.8.0, Type: web
2023-10-22 18:48:33,256 [websockets.py:on_close()] - Websocket Closed: ID: 4141326640 Close Code: None, Close Reason: None, Pong Time Elapsed: 5.85
2023-10-22 19:44:23,198 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 19:44:23,200 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 19:44:33,224 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 19:44:33,227 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 19:50:00,558 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.12
2023-10-22 21:14:29,320 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 21:14:29,321 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 21:14:39,347 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 21:14:39,349 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 21:29:30,341 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 21:29:30,343 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 21:29:40,358 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 21:29:40,361 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 21:44:31,374 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 21:44:31,378 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 21:44:41,382 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 21:44:41,385 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 21:59:22,384 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 21:59:22,386 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 21:59:32,396 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 21:59:32,399 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 22:14:33,404 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 22:14:33,406 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 22:14:43,412 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 22:14:43,415 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 22:17:05,249 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2023-10-22 22:17:05,257 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1698027395.503055, Usage: 2.04%, Memory: 29772 kB
System Time: 1698027396.503558, Usage: 2.02%, Memory: 29772 kB
System Time: 1698027397.504054, Usage: 1.94%, Memory: 29772 kB
System Time: 1698027398.504920, Usage: 2.01%, Memory: 29772 kB
System Time: 1698027399.505486, Usage: 1.92%, Memory: 29772 kB
System Time: 1698027400.505507, Usage: 2.33%, Memory: 29772 kB
System Time: 1698027401.506870, Usage: 1.84%, Memory: 29772 kB
System Time: 1698027402.507319, Usage: 1.87%, Memory: 29772 kB
System Time: 1698027403.510174, Usage: 1.86%, Memory: 29772 kB
System Time: 1698027404.512264, Usage: 4.17%, Memory: 29772 kB
System Time: 1698027405.512774, Usage: 2.08%, Memory: 29772 kB
System Time: 1698027406.513475, Usage: 2.01%, Memory: 29772 kB
System Time: 1698027407.514196, Usage: 1.99%, Memory: 29772 kB
System Time: 1698027408.515299, Usage: 2.0%, Memory: 29772 kB
System Time: 1698027409.517632, Usage: 1.94%, Memory: 29772 kB
System Time: 1698027410.517177, Usage: 2.33%, Memory: 29772 kB
System Time: 1698027411.518875, Usage: 1.85%, Memory: 29772 kB
System Time: 1698027412.519461, Usage: 1.98%, Memory: 29772 kB
System Time: 1698027413.520949, Usage: 1.93%, Memory: 29772 kB
System Time: 1698027414.522576, Usage: 4.13%, Memory: 29772 kB
System Time: 1698027415.522397, Usage: 2.09%, Memory: 29772 kB
System Time: 1698027416.523028, Usage: 2.02%, Memory: 29772 kB
System Time: 1698027417.523706, Usage: 1.98%, Memory: 29772 kB
System Time: 1698027418.524417, Usage: 2.01%, Memory: 29772 kB
System Time: 1698027419.526133, Usage: 1.98%, Memory: 29772 kB
System Time: 1698027420.526216, Usage: 2.34%, Memory: 29772 kB
System Time: 1698027421.527533, Usage: 1.8%, Memory: 29772 kB
System Time: 1698027422.528447, Usage: 1.96%, Memory: 29772 kB
System Time: 1698027423.529307, Usage: 1.94%, Memory: 29772 kB
System Time: 1698027424.531188, Usage: 4.12%, Memory: 29772 kB
CPU Temperature: 54.043
2023-10-22 22:17:05,261 [proc_stats.py:_handle_shutdown()] - Throttled Flags: 
2023-10-22 23:14:27,396 [machine.py:_find_public_ip()] - Failed to detect local IP address
2023-10-22 23:14:27,399 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2023-10-22 23:14:37,402 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.195
2023-10-22 23:14:37,407 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.195
2023-10-22 23:17:20,538 [websockets.py:write_to_socket()] - Websocket closed while writing: 3902156152
2023-10-22 23:17:25,368 [websockets.py:on_close()] - Websocket Closed: ID: 3902156152 Close Code: None, Close Reason: None, Pong Time Elapsed: 45.00
